apiVersion: v1
kind: Pod
metadata:
    name: ffmpeg-build
    namespace: rimo-step
spec:
    runtimeClassName: nvidia
    nodeSelector:
        use-case: rimo-step
    tolerations:
        - key: rimo-step
          operator: Exists
          effect: NoSchedule
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
    containers:
        - name: build
          image: nvidia/cuda:12.6.3-devel-ubuntu22.04
          command: ['sleep', 'infinity']
          env:
              - name: NVIDIA_VISIBLE_DEVICES
                value: all
              - name: NVIDIA_DRIVER_CAPABILITIES
                value: compute,video,utility
              - name: LD_LIBRARY_PATH
                value: /usr/local/nvidia/lib64:/usr/local/nvidia/lib:/usr/lib/x86_64-linux-gnu
          resources:
              limits:
                  nvidia.com/gpu: 1
                  memory: '16Gi'
                  cpu: '8'
              requests:
                  nvidia.com/gpu: 1
                  memory: '12Gi'
                  cpu: '4'
          volumeMounts:
              - name: sfx-cues
                mountPath: /app/cues
    volumes:
        - name: sfx-cues
          configMap:
              name: sfx-cues
